[embedding]
provider = "litellm"
base_model = "jina_ai/jina-embeddings-v3"
base_dimension = 1024
batch_size = 16
concurrent_request_limit = 2

[completion_embedding]
provider = "litellm"
base_model = "jina_ai/jina-embeddings-v3"
base_dimension = 1024
batch_size = 16
concurrent_request_limit = 2

[ingestion]
provider = "r2r"
chunking_strategy = "recursive"
chunk_size = 1024
chunk_overlap = 512
automatic_extraction = false
skip_document_summary = true

[completion]
provider = "litellm"
concurrent_request_limit = 16

    [completion.generation_config]
    model = "deepseek/deepseek-chat"
    temperature = 0.1
    top_p = 1
    max_tokens_to_sample = 1024
    stream = false

[database]
provider = "postgres"

[file]
provider = "postgres"

[auth]
require_authentication = false

[orchestration]
provider = "simple"
